version: '3.8'

services:
  task.list.by.developer:
    image: mysql
    restart: always
    container_name: task.list.by.developer
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task-list-by-developer
      MYSQL_USER: luis.saravia
      MYSQL_PASSWORD: password
    ports:
      - "3322:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    networks:
      - task-list-network

  backend:
    depends_on:
      task.list.by.developer:
        condition: service_healthy
    image: saraviadeveloper/api-task-list
    restart: always
    
    ports:
      - "3001:3001"
    networks:
      - task-list-network

  frontend:
    depends_on:
      - backend
    image: saraviadeveloper/frontend-task-list
    restart: always

    ports:
      - "4410:4410"
    networks:
      - task-list-network

volumes:
  db_data: 

networks:
  task-list-network:
    name: "task-list-network"
    driver: bridge
    # external: true
